name: ci

on:
  pull_request: {}
  push: {}
  release:
    types: [published]

jobs:
  build-release:
    name: Build release Executable (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
    env:
      BINARY_EXTENSION: ${{ endsWith(matrix.target, '-msvc') && '.exe' || '' }}
      PATH_BINARY: ${{ github.workspace }}/target/${{ matrix.TARGET }}/release/simple-http-server${{ matrix.EXTENSION }}${{ endsWith(matrix.target, '-msvc') && '.exe' || '' }}
      OPENSSL_STATIC: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          components: clippy
          target: ${{ matrix.target }}
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt update -y && sudo apt install libssl-dev -y
      - if: ${{ matrix.os == 'macos-latest' }}
        run: brew install openssl
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --bin simple-http-server --locked --target=${{ matrix.TARGET }} -- -C opt-level=z -C panic=abort -C link-args=-Wl,-s
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}-simple-http-server${{ env.BINARY_EXTENSION }}
          path: ${{ env.PATH_BINARY }}
      - name: Evaluate shasum
        run: echo -n $(shasum -ba 256 ${{ env.PATH_BINARY }} | cut -d " " -f 1) > ${{ env.PATH_BINARY }}.sha256
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}-simple-http-server.sha256
          path: ${{ env.PATH_BINARY }}.sha256

      - name: '[Optional] Publish Artifact'
        if: ${{ github.event_name == 'release' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.PATH_BINARY }}
          asset_name: ${{ matrix.target }}-simple-http-server${{ env.BINARY_EXTENSION }}
          tag: ${{ github.ref }}
          overwrite: true
      - name: '[Optional] Publish Artifact (shasum)'
        if: ${{ github.event_name == 'release' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.PATH_BINARY }}.sha256
          asset_name: ${{ matrix.target }}-simple-http-server${{ env.BINARY_EXTENSION }}.sha256
          tag: ${{ github.ref }}
          overwrite: true
